// Code generated by MockGen. DO NOT EDIT.
// Source: api_metadata.go
//
// Generated by this command:
//
//	mockgen -source=api_metadata.go -destination=../mocks/api_metadata.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
